spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/todolist
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
